######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 19 12:48:54 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h window.h Wuziqi.h
SOURCES += dialog.cpp main.cpp window.cpp Wuziqi.cpp
